source_path : "ABSOLUTE_PATH_TO/Dropbox/olivierdeserres/"
target_path : "ABSOLUTE_PATH_TO/olivierdeserres.github.io/dev/"
templates_path : "ABSOLUTE_PATH_TO/olivierdeserres.github.io/templates"
temporaty_path : "ABSOLUTE_PATH_TO/tmp"
force_remove : True
update_delay : 60
image_file_extensions :
    - ".jpg"
    - ".jpeg"
    - ".png"